config/routes.rb
Rails.application.routes.draw do
  get 'others/welcome'
  root 'others#welcome'
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/show', to: 'users#show'
  post 'attendances/clock_in_just_now', to: 'attendances#clock_in_just_now'
  post 'attendances/clock_out_just_now', to: 'attendances#clock_out_just_now'
  resources :users, only: [] do
    resources :attendances, except: :show
    get 'attendances/weekly', to: 'attendances#weekly'
    get 'attendances/monthly', to: 'attendances#monthly'
    get 'attendances/summary', to: 'attendances#summary'
    get 'attendances/labor_reform', to: 'attendances#labor_standard_law_board'
  end
  namespace :api do
    resources :users, only: [] do
      resources :attendances, only: [:create] do
        collection do
          get 'by_day_of_week'
        end
      end
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validates :date, uniqueness: { scope: :user }, presence: true
  validates :clock_in_time, presence: true
  validates :clock_out_time, presence: true
  validate :time_validation

  enum division: { ordinary: 0, off_day: 1, morning_off: 2, afternoon_off: 3 }

  def working_seconds
    diff_sec_between_clock_in_out - resting_sec
  end

  def extra_working_seconds
    working_seconds - normal_working_seconds
  end

  def normal_working_seconds
    case
    when ordinary?
      (work_end_time - work_start_time) - (rest_end_time - rest_start_time)
    when off_day?
      0.0
    when morning_off?
      work_end_time - rest_end_time
    when afternoon_off?
      rest_start_time - work_start_time
    end
  end

  def time_validation
    return if clock_in_time.blank? || clock_out_time.blank?

    if clock_in_time >= clock_out_time
      errors.add(:clock_out_time, 'は出勤時刻より後にしてください')
    end
  end

  def clock_in_time
    self[:clock_in_time].present? ? Time.zone.parse(self[:clock_in_time].to_s(:time)) : nil
  end

  def clock_out_time
    self[:clock_out_time].present? ? Time.zone.parse(self[:clock_out_time].to_s(:time)) : nil
  end

  def work_start_time
    Time.zone.parse(user.work_start_time.to_s(:time))
  end

  def work_end_time
    Time.zone.parse(user.work_end_time.to_s(:time))
  end

  def rest_start_time
    Time.zone.parse(user.rest_start_time.to_s(:time))
  end

  def rest_end_time
    Time.zone.parse(user.rest_end_time.to_s(:time))
  end

  private

  def diff_sec_between_clock_in_out
    clock_out_time - clock_in_time
  end

  def resting_sec
    case
    when clock_in_before_rest_start? && clock_out_after_rest_end?
      rest_end_time - rest_start_time
    when clock_in_before_rest_start? && clock_out_during_recess?
      clock_out_time - rest_start_time
    when clock_in_before_rest_start? && clock_out_before_rest_start?
      0.0
    when clock_in_during_recess? && clock_out_after_rest_end?
      rest_end_time - clock_in_time
    when clock_in_during_recess? && clock_out_during_recess?
      clock_out_time - clock_in_time
    else
      0.0
    end
  end

  def clock_in_before_rest_start?
    clock_in_time <= rest_start_time
  end

  def clock_in_during_recess?
    clock_in_time.between?(rest_start_time, rest_end_time)
  end

  def clock_in_after_rest_end?
    rest_end_time <= clock_in_time
  end

  def clock_out_before_rest_start?
    clock_out_time <= rest_start_time
  end

  def clock_out_during_recess?
    clock_out_time.between?(rest_start_time, rest_end_time)
  end

  def clock_out_after_rest_end?
    rest_end_time <= clock_out_time
  end
end

app/controllers/api/attendances_controller.rb
class Api::AttendancesController < Api::BaseController
  def create
    attendances = current_user.attendances.where(date: @start_date..@end_date)
    @dashboard = Dashboard.new(attendances)
    @days_all = (@end_date - @start_date).to_i + 1
    @all_seconds = @end_date.to_time - @start_date.to_time + 60
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[show edit update destroy]
  include ApplicationHelper

  def summary
    now = Time.current
    attendances = current_user.attendances.where(date: now.beginning_of_month..now)
    @dashboard = Dashboard.new(attendances)
    @days_all = (now.to_date - now.beginning_of_month.to_date).to_i + 1
    @all_seconds = now.to_time - now.beginning_of_month.to_time + 60
  end

  def labor_standard_law_board
    @labor_standard_law_board = LaborStandardLawBoard.new(current_user)
  end

  def clock_in_just_now
    flash_message = if current_user.attendances.find { |a| a.date == Time.zone.now.to_date }
                      { alert: '本日の勤怠情報はすでに登録されています' }
                    else
                      attendance_params = { date: Time.zone.now.to_date, clock_in_time: Time.zone.now, clock_out_time: current_user.work_end_time }
                      attendance = current_user.attendances.build(attendance_params)
                      if attendance.save
                        { notice: '勤怠情報を登録しました' }
                      else
                        { alert: '出勤時刻は就業時刻より前である必要があります' }
                      end
                    end
    redirect_to user_attendances_path(current_user.id), flash_message
  end

  def clock_out_just_now
    attendance = current_user.attendances.find { |a| a.date == Time.zone.now.to_date }
    flash_message = if attendance
                      attendance_params = { clock_out_time: Time.zone.now }
                      if attendance.update(attendance_params)
                        { notice: '勤怠情報を更新しました' }
                      else
                        { alert: '退勤時刻は始業時刻より後である必要があります' }
                      end
                    else
                      attendance_params =
                        { date: Time.zone.now.to_date, clock_in_time: current_user.work_start_time, clock_out_time: Time.zone.now }
                      attendance = current_user.attendances.build(attendance_params)
                      if attendance.save
                        { notice: '勤怠情報を登録しました' }
                      else
                        { alert: '退勤時刻は始業時刻より後である必要があります' }
                      end
                    end
    redirect_to user_attendances_path(current_user.id), flash_message
  end

  def index
    @attendances = current_user.attendances
  end

  def weekly
    @dashboards = []
    current_user.attendances.group_by_week(&:date).each do |_key, value|
      @dashboards << Dashboard.new(value)
    end
  end

  def monthly
    @dashboards = []
    current_user.attendances.group_by_month(&:date).each do |_key, value|
      @dashboards << Dashboard.new(value)
    end
  end

  def new
    @attendance = current_user.attendances.build
  end

  def edit
  end

  def create
    @attendance = current_user.attendances.build(attendance_params)

    if @attendance.save
      redirect_to user_attendances_path(current_user.id), notice: '勤怠情報を登録しました'
    else
      render :new
    end
  end

  def update
    if @attendance.update(attendance_params)
      redirect_to user_attendances_path(current_user.id), notice: '勤怠情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @attendance.destroy
    redirect_to user_attendances_path(current_user.id), notice: '勤怠情報を削除しました'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attendance_params
    params.require(:attendance).permit(:clock_in_time, :clock_out_time, :date, :division)
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def default_clock_in_time(mode, attendance)
    mode == 'New' ? current_user.work_start_time.to_s(:time) : attendance.clock_in_time.to_s(:time)
  end

  def default_clock_out_time(mode, attendance)
    mode == 'New' ? current_user.work_end_time.to_s(:time) : attendance.clock_out_time.to_s(:time)
  end

  def default_date(mode, attendance)
    mode == 'New' ? Date.today : attendance.date
  end

  def default_check(attendance)
    attendance.off_day?
  end

  def mode_to_ja(mode)
    mode == 'New' ? '登録' : '編集'
  end

  def warning_message(month, extra_working_seconds)
    seconds = (80 * 60 * 60) * month.to_i - extra_working_seconds
    if seconds >= 0
      "今月あと #{convert_to_hh_mm_from_sec(seconds)} 時間残業すると上限に到達します"
    else
      "今月の残業時間を #{convert_to_hh_mm_from_sec(-seconds)} 時間削減すると上限に収まります"
    end
  end

  private

  def basic_opts
    {
      discrete: true,
      legend: false,
      download: true,
      label: ' ',
      ytitle: '時間',
      suffix: ' 時間'
    }
  end
end

app/views/attendances/_all_group_by_day.html.erb
<div id="all_group_by_day">
  <%= column_chart @dashboard.all_working_hours_group_by_day, basic_opts %>
</div>

app/views/attendances/_all_group_by_month.html.erb
<div id="all_group_by_month">
  <%= column_chart @dashboard.all_working_hours_group_by_month, basic_opts %>
</div>

app/views/attendances/_all_working_hours.html.erb
<div class="info-box-content" id="all_working_hours">
  <span class="info-box-text">総労働時間</span>
  <span class="info-box-number"><%= convert_to_hh_mm_from_sec(@dashboard.all_working_seconds) %></span>
  <div class="progress">
    <div class="progress-bar bg-aqua" style="width: <%= (@dashboard.all_working_seconds / @all_seconds) * 100 %>%"></div>
  </div>
  <span class="progress-description">
    総時間の<strong><%= (@dashboard.all_working_seconds / @all_seconds * 100).to_i %>%</strong>
  </span>
</div>

app/views/attendances/_average_extra_working_hours.html.erb
<div class="info-box-content" id="average_extra_working_hours">
  <span class="info-box-text">平均残業時間</span>
  <span class="info-box-number"><%= convert_to_hh_mm_from_sec(@dashboard.average_extra_working_seconds) %></span>
</div>

app/views/attendances/_avg_by_day_of_week.html.erb
<div id="avg_by_day_of_week">
  <%= column_chart @dashboard.average_extra_working_hours_by_day_of_week, basic_opts %>
</div>

app/views/attendances/_days_worked.html.erb
<div class="info-box-content" id="days_worked">
  <span class="info-box-text">就業日数</span>
  <span class="info-box-number"><%= @dashboard.days_worked %> 日</span>
  <div class="progress">
    <div class="progress-bar bg-red" style="width: <%= (@dashboard.days_worked / @days_all.to_f) * 100 %>%"></div>
  </div>
  <span class="progress-description">
    <strong><%= @days_all %></strong> 日中
  </span>
</div>

app/views/attendances/_form.html.erb
<section class="content-header">
  <h1>
    <i class="fa fa-clock-o"></i> 勤怠<%= mode_to_ja(mode) %>
    <small>omae</small>
  </h1>
  <ol class="breadcrumb">
    <li>勤怠情報</li>
    <li><%= link_to '日次勤怠', user_attendances_path(current_user.id) %></li>
    <li class="active"><%= mode_to_ja(mode) %></li>
  </ol>
</section>
<hr>

<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">勤怠<%= mode_to_ja(mode) %></h3>
    <%= link_to '', user_attendance_path(current_user.id, attendance), method: :delete, data: { confirm: '削除しますか?' }, class: "btn btn-danger fa fa-trash pull-right" if mode == 'Edit' %>
  </div>
  <div class="box-body">
    <%= form_with(model: attendance, url: path, local: true) do |form| %>
      <% if attendance.errors.any? %>
        <% attendance.errors.full_messages.each do |message| %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">close</span>
            </button>
            <%= message %>
          </div>
        <% end %>
      <% end %>
      <div class="row">
        <div class="col-sm-6 col-md-2">
          <div class="form-group">
            <%= form.label '勤怠区分' %>
            <%= form.select :division, Attendance.divisions.keys.map { |k| [I18n.t("enums.attendance.division.#{k}"), k] }, {}, { class: "form-control" } %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= form.label :date %>
            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <%= form.text_field :date, class: "form-control date", autocomplete: "off", value: default_date(mode, attendance) %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :clock_in_time %><br />
            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-clock-o"></i>
              </div>
              <%= form.text_field :clock_in_time, class: "form-control time", value: default_clock_in_time(mode, attendance) %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= form.label :clock_out_time %><br>
            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-clock-o"></i>
              </div>
              <%= form.text_field :clock_out_time, class: "form-control time", value: default_clock_out_time(mode, attendance) %>
            </div>
          </div>
        </div>
      </div>
      <div class="actions">
        <%= form.submit mode == 'New' ? '登録' : '更新', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/attendances/dashboard.html.erb
<section class="content-header">
  <h1>
    <i class="fa fa-area-chart"></i> サマリー
    <small>omae</small>
  </h1>
  <ol class="breadcrumb">
    <li>ダッシュボード</li>
    <li class="active">サマリー</li>
  </ol>
</section>
<hr>

<div class="row">
  <%= form_tag api_user_attendances_path(current_user), remote: true do %>
    <div class="col-lg-6 col-xs-9">
      <div class="input-daterange input-group" id="datepicker">
        <input type="text" class="input-sm form-control date" autocomplete="off" name="start_date" id="start_date" value=<%= Time.current.beginning_of_month %>/>
        <span class="input-group-addon">〜</span>
        <input type="text" class="input-sm form-control date" autocomplete="off" name="end_date" id="end_date" value=<%= Time.current %>/>
      </div>
    </div>
    <div class="col-xs-1">
      <%= button_tag '表示', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<hr>

<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-aqua">
        <i class="fa fa-building"></i>
      </span>
      <%= render 'all_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-green">
        <i class="fa fa-building-o"></i>
      </span>
      <%= render 'all_extra_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-yellow">
        <i class="fa fa-balance-scale"></i>
      </span>
      <%= render 'average_extra_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-red">
        <i class="fa fa-calendar-check-o"></i>
      </span>
      <%= render 'days_worked' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-sm-12">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs pull-right">
        <li class="active">
          <a href="#group_by_day" data-toggle="tab">日次</a>
        </li>
        <li>
          <a href="#group_by_week" data-toggle="tab">週次</a>
        </li>
        <li>
          <a href="#group_by_month" data-toggle="tab">月次</a>
        </li>
        <li class="pull-left header">
          総労働時間
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="group_by_day">
          <%= render 'all_group_by_day' %>
        </div>
        <div class="tab-pane" id="group_by_week">
          <%= render 'all_group_by_week' %>
        </div>
        <div class="tab-pane" id="group_by_month">
          <%= render 'all_group_by_month' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-12">
    <div class="box box-danger">
      <div class="box-header with-border">
        <h3 class="box-title">曜日別 平均残業時間</h3>
      </div>
      <div class="box-body">
        <%= render 'avg_by_day_of_week' %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/edit.html.erb
<%= render 'form', { attendance: @attendance, path: user_attendance_path(current_user.id), mode: 'Edit' }%>

app/views/attendances/index.html.erb
<section class="content-header">
  <h1>
    <i class="fa fa-database"></i> 日次勤怠
    <small>omae</small>
  </h1>
  <ol class="breadcrumb">
    <li>勤怠情報</li>
    <li class="active">日次勤怠</li>
  </ol>
</section>
<hr>

<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">日次勤怠一覧</h3>
      <div class="btn-group pull-right">
        <%= link_to '新規登録', new_user_attendance_path, class: "btn btn-success" %>
        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to '出勤なう', attendances_clock_in_just_now_path, method: :post %></li>
          <li><%= link_to '退勤なう', attendances_clock_out_just_now_path, method: :post %></li>
        </ul>
      </div>
  </div>
  <div class="box-body">
    <table class="table table-bordered table-hover dataTable" id="attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>労働時間</th>
          <th>残業時間</th>
          <th>出勤時刻</th>
          <th>退勤時刻</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |attendance| %>
          <tr data-link="<%= edit_user_attendance_path(current_user.id, attendance) %>" class="clickable<%= ' danger' if attendance.off_day? %>">
            <td><%= "#{attendance.date}" %></td>
            <td><%= "#{convert_to_hh_mm_from_sec(attendance.working_seconds)}" %></td>
            <td><%= "#{convert_to_hh_mm_from_sec(attendance.extra_working_seconds)}" %></td>
            <td><%= "#{attendance.clock_in_time.to_s(:time)}" %></td>
            <td><%= "#{attendance.clock_out_time.to_s(:time)}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  $("tr[data-link]").click(function() {
    window.location = $(this).data("link")
  })
</script>

app/views/attendances/monthly.html.erb
<section class="content-header">
  <h1>
    <i class="fa fa-calendar-o"></i> 月次勤怠
    <small>omae</small>
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to '勤怠情報', root_path %></li>
    <li class="active">月次勤怠</li>
  </ol>
</section>
<hr>

<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">月次勤怠一覧</h3>
  </div>
  <div class="box-body">
    <table class="table table-bordered table-hover dataTable" id="attendances">
      <thead>
        <tr>
          <th>年月</th>
          <th>総労働時間</th>
          <th>総残業時間</th>
          <th>平均残業時間</th>
          <th>就業日数</th>
        </tr>
      </thead>
      <tbody>
        <% @dashboards.each do |dashboard| %>
          <tr>
            <td><%= "#{dashboard.attendances.first.date.strftime('%Y年%m月')}" %></td>
            <td><%= "#{convert_to_hh_mm_from_sec(dashboard.all_working_seconds)}" %></td>
            <td><%= "#{convert_to_hh_mm_from_sec(dashboard.all_extra_working_seconds)}" %></td>
            <td><%= "#{convert_to_hh_mm_from_sec(dashboard.average_extra_working_seconds)}" %></td>
            <td><%= "#{dashboard.days_worked}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/attendances/new.html.erb
<%= render 'form', { attendance: @attendance, path: user_attendances_path(current_user.id), mode: 'New' } %>

app/views/attendances/sammary.html.erb
<section class="content-header">
  <h1>
    <i class="fa fa-area-chart"></i> サマリー
    <small>omae</small>
  </h1>
  <ol class="breadcrumb">
    <li>ダッシュボード</li>
    <li class="active">サマリー</li>
  </ol>
</section>
<hr>

<div class="row">
  <%= form_tag api_user_attendances_path(current_user), remote: true do %>
    <div class="col-lg-6 col-xs-9">
      <div class="input-daterange input-group" id="datepicker">
        <input type="text" class="input-sm form-control date" autocomplete="off" name="start_date" id="start_date" value=<%= Time.current.beginning_of_month %>/>
        <span class="input-group-addon">〜</span>
        <input type="text" class="input-sm form-control date" autocomplete="off" name="end_date" id="end_date" value=<%= Time.current %>/>
      </div>
    </div>
    <div class="col-xs-1">
      <%= button_tag '表示', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<hr>

<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-aqua">
        <i class="fa fa-building"></i>
      </span>
      <%= render 'all_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-green">
        <i class="fa fa-building-o"></i>
      </span>
      <%= render 'all_extra_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-yellow">
        <i class="fa fa-balance-scale"></i>
      </span>
      <%= render 'average_extra_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-red">
        <i class="fa fa-calendar-check-o"></i>
      </span>
      <%= render 'days_worked' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-sm-12">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs pull-right">
        <li class="active">
          <a href="#group_by_day" data-toggle="tab">日次</a>
        </li>
        <li>
          <a href="#group_by_week" data-toggle="tab">週次</a>
        </li>
        <li>
          <a href="#group_by_month" data-toggle="tab">月次</a>
        </li>
        <li class="pull-left header">
          総労働時間
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="group_by_day">
          <%= render 'all_group_by_day' %>
        </div>
        <div class="tab-pane" id="group_by_week">
          <%= render 'all_group_by_week' %>
        </div>
        <div class="tab-pane" id="group_by_month">
          <%= render 'all_group_by_month' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-12">
    <div class="box box-danger">
      <div class="box-header with-border">
        <h3 class="box-title">曜日別 平均残業時間</h3>
      </div>
      <div class="box-body">
        <%= render 'avg_by_day_of_week' %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/summary.html.erb
<section class="content-header">
  <h1>
    <i class="fa fa-area-chart"></i> サマリー
    <small>omae</small>
  </h1>
  <ol class="breadcrumb">
    <li>ダッシュボード</li>
    <li class="active">サマリー</li>
  </ol>
</section>
<hr>

<div class="row">
  <%= form_tag api_user_attendances_path(current_user), remote: true do %>
    <div class="col-lg-6 col-xs-9">
      <div class="input-daterange input-group" id="datepicker">
        <input type="text" class="input-sm form-control date" autocomplete="off" name="start_date" id="start_date" value=<%= Time.current.beginning_of_month %>/>
        <span class="input-group-addon">〜</span>
        <input type="text" class="input-sm form-control date" autocomplete="off" name="end_date" id="end_date" value=<%= Time.current %>/>
      </div>
    </div>
    <div class="col-xs-1">
      <%= button_tag '表示', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<hr>

<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-aqua">
        <i class="fa fa-building"></i>
      </span>
      <%= render 'all_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-green">
        <i class="fa fa-building-o"></i>
      </span>
      <%= render 'all_extra_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-yellow">
        <i class="fa fa-balance-scale"></i>
      </span>
      <%= render 'average_extra_working_hours' %>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-red">
        <i class="fa fa-calendar-check-o"></i>
      </span>
      <%= render 'days_worked' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-sm-12">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs pull-right">
        <li class="active">
          <a href="#group_by_day" data-toggle="tab">日次</a>
        </li>
        <li>
          <a href="#group_by_week" data-toggle="tab">週次</a>
        </li>
        <li>
          <a href="#group_by_month" data-toggle="tab">月次</a>
        </li>
        <li class="pull-left header">
          総労働時間
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="group_by_day">
          <%= render 'all_group_by_day' %>
        </div>
        <div class="tab-pane" id="group_by_week">
          <%= render 'all_group_by_week' %>
        </div>
        <div class="tab-pane" id="group_by_month">
          <%= render 'all_group_by_month' %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-12">
    <div class="box box-danger">
      <div class="box-header with-border">
        <h3 class="box-title">曜日別 平均残業時間</h3>
      </div>
      <div class="box-body">
        <%= render 'avg_by_day_of_week' %>
      </div>
    </div>
  </div>
</div>