config/routes.rb
Rails.application.routes.draw do
  get 'others/welcome'
  root 'others#welcome'
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'users/show', to: 'users#show'
  post 'attendances/clock_in_just_now', to: 'attendances#clock_in_just_now'
  post 'attendances/clock_out_just_now', to: 'attendances#clock_out_just_now'
  resources :users, only: [] do
    resources :attendances, except: :show
    get 'attendances/weekly', to: 'attendances#weekly'
    get 'attendances/monthly', to: 'attendances#monthly'
    get 'attendances/summary', to: 'attendances#summary'
    get 'attendances/labor_reform', to: 'attendances#labor_standard_law_board'
  end
  namespace :api do
    resources :users, only: [] do
      resources :attendances, only: [:create] do
        collection do
          get 'by_day_of_week'
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-49022589-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-49022589-2');
    </script>

    <title>Omae</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body class="skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">
        <a href=<%= signed_in? ? user_attendances_summary_path(current_user.id) : root_path %> class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>O</b>MAE</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>O</b>MAE</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown notifications-menu">
                <% if user_signed_in? %>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.user_name %></a>
                  <ul class="dropdown-menu">
                    <li>
                      <ul class="menu">
                        <li>
                          <%= link_to users_show_path do %>
                            <i class="fa fa-info-circle"></i>アカウント情報
                          <% end %>
                        </li>
                        <li>
                          <%= link_to destroy_user_session_path, method: :delete do %>
                            <i class="fa fa-sign-out"></i>ログアウト
                          <% end %>
                        </li>
                      </ul>
                    </li>
                  </ul>
                <% else %>
                  <%= link_to 'ログイン / 登録', new_user_session_path %>
                <% end %>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar Menu -->
          <ul class="sidebar-menu" data-widget="tree">
            <!-- Optionally, you can add icons to the links -->
            <% if user_signed_in? %>
              <li class="header">ダッシュボード</li>
              <li><a href=<%= user_attendances_summary_path(current_user.id) %>><i class="fa fa-area-chart"></i><span>サマリー</span></a></li>
              <li><a href=<%= user_attendances_labor_reform_path(current_user.id) %>><i class="fa fa-bar-chart"></i><span>労基法ボード</span></a></li>
              <li class="header">勤怠データ</li>
              <li><a href=<%= user_attendances_path(current_user.id) %>><i class="fa fa-database"></i><span>日次勤怠</span></a></li>
              <li><a href=<%= user_attendances_weekly_path(current_user.id) %>><i class="fa fa-table"></i><span>週次勤怠</span></a></li>
              <li><a href=<%= user_attendances_monthly_path(current_user.id) %>><i class="fa fa-calendar-o"></i><span>月次勤怠</span></a></li>
            <% end %>
          </ul>
          <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">

        <!-- Main content -->
        <section class="content container-fluid">
          <% if flash[:notice] %>
            <div class="alert alert-info alert-dismissible">
              <i class="icon fa fa-info"></i><%= notice %>
              <button type="button" class="close" data-dismiss="alert" aria-label="close"><i class="fa fa-close"></i></button>
            </div>
          <% elsif flash[:alert] %>
            <div class="alert alert-danger alert-dismissible">
              <i class="icon fa fa-warning"></i><%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="close"><i class="fa fa-close"></i></button>
            </div>
          <% end %>
          <%= yield %>
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <strong>Copyright &copy; 2019 OMAE</strong>
      </footer>
    </div>
    <%= javascript_include_tag "timepicker" %>
    <%= javascript_include_tag "datepicker" %>
  </body>
</html>